import "./globals.css";

import type { Metadata } from "next";
import { Rajdhani, Redacted_Script } from "next/font/google";
import Footer from "@/src/components/Footer/Footer";
import { ThemeProvider } from "../src/components/providers/providers";
import Header from "@/src/components/Header/Header";
import { siteConfig } from "@/src/config/site";
import RespectMotionPreferences from "@/src/components/providers/RespectMotionPreferences";
import { TailwindIndicator } from "@/src/components/providers/Tailwind-indicator";
import { CSSProperties } from "react";

const rajdhani = Rajdhani({ weight: "700", subsets: ["latin"] });

const loadingFont = Redacted_Script({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Itai Mizlish",
  description: "Generated by create next app",
  keywords: [
    "Next.js",
    "Tailwind",
    "Framer-Motion",
    "Itai Mizlish",
    "ui-shadcn",
  ],
  authors: [
    {
      name: "ItaiM",
      url: "https://itaimiz.com",
    },
  ],
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://itaimiz.com",
    title: "Itai Mizlish",
    description: "Itai Mizlish - Frontend development done to the fullest 🪐",
    siteName: "Itai Mizlish",
    images: [
      {
        url: siteConfig.image,
        width: 1200,
        height: 630,
        alt: siteConfig.name,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Itai Mizlish",
    description: "",
    images: [siteConfig.image],
    creator: "@IMizlish",
  },
  creator: "ItaiM18",
  icons: {
    icon: "/vercel.svg",
    shortcut: "/vercel.svg",
    apple: "/vercel.svg",
  },
};
export default function RootLayout({
  params,
  children,
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html
      lang="en"
      // style={
      //   {
      //     "--font-family-loading": loadingFont.style.fontFamily,
      //   } as CSSProperties
      // }
    >
      <body className={rajdhani.className}>
        <RespectMotionPreferences>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <Header />
            {children}
            <Footer />
            <TailwindIndicator />
          </ThemeProvider>
        </RespectMotionPreferences>
      </body>
    </html>
  );
}
