import "./globals.css";
import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import Footer from "@/src/components/Footer/Footer";
import { ThemeProvider } from "../src/components/providers/providers";
import Header from "@/src/components/Header/Header";
const rajdhani = Rajdhani({ weight: "700", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Itai Mizlish",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rajdhani.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
